name: Sync Gmail to Airtable

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

    - name: Sync Gmail to Airtable
      env:
        AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
        AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
        AIRTABLE_TABLE_NAME: ${{ secrets.AIRTABLE_TABLE_NAME }}
        GMAIL_CREDENTIALS: ${{ secrets.GMAIL_CREDENTIALS }}
      run: |
        python gmail_to_airtable.py
