name: Gmail to Airtable Sync
on:
  workflow_dispatch:
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
    - name: Debug Token Format
      run: |
        # Créer le fichier token.json avec le secret
        echo '${{ secrets.GMAIL_TOKEN }}' > token_raw.txt
        
        # Vérifier les premiers caractères (attention à ne pas exposer tout le contenu)
        echo "Premiers caractères du token (devrait commencer par {) :"
        head -c 10 token_raw.txt
        
        # Vérifier si c'est un JSON valide
        echo "Validation du format JSON :"
        cat token_raw.txt | python -c "import sys, json; json.load(sys.stdin); print('Token JSON valide!')" || echo "Token JSON invalide"
        
        # Ne pas afficher le contenu complet pour des raisons de sécurité
